services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  
  app:
    build: .
    container_name: multi-server
    ports:
      - "4444:4444"
    depends_on:
      - redis
