version: '3'
services:
  redis-server:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379" # Mapeamos el puerto 6379 del host al puerto 6379 del contenedor
    volumes:
      - redis-data:/data # Mapeamos un volumen para persistir los datos de Redis
    restart: always # Asegura que el contenedor se reinicie si falla

volumes:
  redis-data:
